[Autologin]
Relogin=false
Session=hyprland
User=rafeu

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=hypr-login

[Users]
MaximumUid=60000
MinimumUid=1000
